num1 = int(input("Digite o primeiro número: "))
num2 = int(input("Digite o segundo número: "))
num3 = int(input("Digite o terceiro número: "))
crescente = sorted([num1, num2, num3])
decrescente = sorted([num1, num2, num3], reverse=True)
print(f"Ordem crescente: {crescente[0]}, {crescente[1]}, {crescente[2]}")
print(f"Ordem decrescente: {decrescente[0]}, {decrescente[1]}, {decrescente[2]}")